/* Author:  Leonardo Trevisan Silio
 * Date:    11/07/2024
 */
using System;
using System.Text;
using System.Collections.Generic;

namespace Blindness.Abstracts;

/// <summary>
/// A builder to generate a CSharp class file.
/// </summary>
public class ClassBuilder
{
    string className = "MyClass";
    readonly List<string> usings = [];
    readonly List<string> baseTypes = [];
    readonly List<string> attributes = [];
    readonly StringBuilder classCode = new();
    string tabInfo = "\t";
    const char tab = '\t';

    public ClassBuilder SetClassName(string className)
    {
        this.className = className;
        return this;
    }

    public ClassBuilder AddBaseType(string type)
    {
        if (type is null)
            throw new ArgumentNullException(nameof(type));
        
        if (baseTypes.Contains(type))
            return this;
        
        baseTypes.Add(type);
        return this;
    }

    public ClassBuilder AddUsing(string reference)
    {
        if (reference is null)
            throw new ArgumentNullException(nameof(reference));
        
        if (usings.Contains(reference))
            return this;
        
        usings.Add(reference);
        return this;
    }

    public ClassBuilder AddAttribute(string attribute)
    {
        if (attribute is null)
            throw new ArgumentNullException(nameof(attribute));
        
        if (attributes.Contains(attribute))
            return this;
        
        attributes.Add(attribute);
        return this;
    }

    public ClassBuilder AddLineCode(string code)
    {
        if (code is null)
            throw new ArgumentNullException(nameof(code));
        
        if (code is null)
            return this;
        
        code = tabInfo + code
            .Replace("\r", "")
            .Replace("\n", "\n" + tabInfo);
        classCode.AppendLine(code);
        return this;
    }

    // public ClassBuilder AddProperty(string type, string name, string get, string set)
    // {
    //     AddLineCode($"public {type} {name} ")
    // }

    public ClassBuilder AddScope()
    {
        tabInfo += tab;
        return this;
    }

    public ClassBuilder RemoveScope()
    {
        if (tabInfo.Length == 0)
            return this;
        
        tabInfo = tabInfo[1..];
        return this;
    }

    /// <summary>
    /// Build and get the C# code.
    /// </summary>
    public string Build()
    {
        StringBuilder usingsCode = new();
        foreach (var reference in usings)
            usingsCode.AppendLine($"using {reference};");
        
        StringBuilder basesCode = new();
        if (baseTypes.Count > 0)
            basesCode.Append(" : ");
        for (int i = 0; i < baseTypes.Count - 1; i++)
        {
            basesCode.Append(baseTypes[i]);
            basesCode.Append(", ");
        }
        basesCode.Append(baseTypes[^1]);

        StringBuilder attributeCode = new();
        foreach (var attribute in attributes)
            attributeCode.AppendLine($"[{attribute}]");

        return
        $$"""
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by a tool.
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------

        {{usingsCode}}
        {{attributeCode}}public partial class {{className}}{{basesCode}}
        {
        {{classCode}}
        }
        """;
    }
}