//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


public partial class MyRealCodeConcrete : MyRealCode
{
	public void OnShow()
		=> ((MyRealCode)this).OnShow();

	public void Show()
	{
	    Console.WriteLine("Starting the show...");
	    OnShow();
	}

}