//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections.Generic;
using Blindness;
using Blindness.Bind;
using Blindness.Core;

[Concrete]
public partial class PanelConcrete : Node, Panel
{
	public PanelConcrete() { }
	public override void Run()
	    => ((Panel)this).OnRun();
	[Binding]
	public String Title
	{
		get => Binding.Get(this).Open<String>(nameof(Title));
		set => Binding.Get(this).Place(nameof(Title), value);
	}
	[Binding]
	public Int32 Width
	{
		get => Binding.Get(this).Open<Int32>(nameof(Width));
		set => Binding.Get(this).Place(nameof(Width), value);
	}
	[Binding]
	public List<INode> Children
	{
		get => Binding.Get(this).Open<List<INode>>(nameof(Children));
		set => Binding.Get(this).Place(nameof(Children), value);
	}

}