//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections.Generic;
using Blindness;
using Blindness.Bind;
using Blindness.Core;

[Concrete]
public partial class TextBoxConcrete : Node, TextBox
{
	public TextBoxConcrete() { }
	public override void Run()
	    => ((TextBox)this).OnRun();
	[Binding]
	public String Title
	{
		get => Binding.Get(this).Open<String>(nameof(Title));
		set => Binding.Get(this).Place(nameof(Title), value);
	}
	[Binding]
	public String Text
	{
		get => Binding.Get(this).Open<String>(nameof(Text));
		set => Binding.Get(this).Place(nameof(Text), value);
	}
	[Binding]
	public Int32 Size
	{
		get => Binding.Get(this).Open<Int32>(nameof(Size));
		set => Binding.Get(this).Place(nameof(Size), value);
	}
	[Binding]
	public Boolean Selected
	{
		get => Binding.Get(this).Open<Boolean>(nameof(Selected));
		set => Binding.Get(this).Place(nameof(Selected), value);
	}

}